export const entreprises = [
  {
    id: 1,
    title: 'Ça commence par nous',
    photo1: "img-01.jpg",
    photo2: "img-02.jpg",
    photo3: "img-03.jpg",
    photo4: "img-04.jpg",
    photo_profile: "img-00.jpg",
    etpName: 'Amina Saan',
    type: 'environnemental',
    tag1: '⛴ manta',
    tag2: '🐠 océan',
    tag3: '🧴 plastique',
    shortPrez: 'Projet écolo-bobo-marin',
    littlePrez: 'pour construire un monde meilleur !',
    needs: '100 000',
    participation: '20 000',
    rentability: '5 000',
    etpCurriculum: 'Amina a commencé à réflechir à ce projet enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ',
    longPrez: 'Chaque seconde, 253 kilos de plastique sont déversés dans les océans. Pour lutter contre la pollution plastique des océans, un autre mastodonte marin suscite lui aussi l\'espoir.Pour laver les océans, le Manta, un voilier de 70 mètres de long, doit permettre de collecter, trier et compacter en mer une grande quantité de macro-déchets plastiques flottant à la surface des océans.',
    firstPage: true,
    alignRight: false,
  },
  {
    id: 2,
    title: 'Impact social',
    photo1: "img-1.jpg",
    photo2: "img-4.jpg",
    photo3: "img-2.jpg",
    photo4: "img-3.jpg",
    photo_profile: "photo_profile3.jpg",
    etpName: 'Annonay Youth Book Festival',
    type: 'social',
    tag1: '📚 livre',
    tag2: '👬 amitié',
    tag3: '🤝🏽 rencontre',
    shortPrez: 'Lire en créant du lien',
    littlePrez: 'pour lire avec nous !',
    needs: '30 000',
    participation: '10 000',
    rentability: '5 000',
    etpCurriculum: 'Charlotte Benson lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    longPrez: 'Cette idée de festival sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
    alignRight: true,
  },
  {
    id: 3,
    title: 'Tech us',
    photo1: "tech-1.jpg",
    photo2: "tech-4.jpg",
    photo3: "tech-5.jpg",
    photo4: "tech-3.jpg",
    photo_profile: "photo_profile5.jpg",
    etpName: 'Logotech',
    type: 'tech',
    tag1: '👩🏽‍🎓 études',
    tag2: '👨🏻‍🚀 future',
    tag3: '🎰 machine',
    shortPrez: 'La technologie au service de l\'environnement',
    littlePrez: 'et rentre dans le monde de demain !',
    needs: '500 000',
    participation: '30 000',
    rentability: '10 000',
    etpCurriculum: 'La méthode simpliste consistant à copier-coller un court texte plusieurs fois (« ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ») a l inconvénient de ne pas permettre une juste appréciation typographique du résultat final.',
    longPrez: 'Généralement, on utilise un texte en faux latin (le texte ne veut rien dire, il a été modifié), le Lorem ipsum ou Lipsum, qui permet donc de faire office de texte d\'attente. Avantage de le mettre en latin est que un opérateur sait au premier coup d\'oeil que la page contenant ces lignes n\'est pas valide, et surtout l\'attention du client n\'est pas dérangée par le contenu, il demeure concentré seulement sur l\'aspect graphique.',
    firstPage: true,
    alignRight: false,
  },
  {
    id: 4,
    title: 'Eduka',
    photo1: "queens-img-01.jpg",
    photo2: "queens-img-03.jpg",
    photo3: "queens-img-02.jpg",
    photo4: "queens-img-04.jpg",
    photo_profile: "photo_profile6.jpg",
    etpName: 'Julien Vidal',
    type: 'éducatif',
    tag1: '🚸 éducation',
    tag2: '👦🏻 jeunesse',
    tag3: '🍀 opportunité',
    shortPrez: 'Le monde de demain sera façonné par ce que nous apprenons aujourd\'hui ',
    littlePrez: 'pour en savoir plus.',
    needs: '100 000',
    participation: '20 000',
    rentability: '5 000',
    etpCurriculum: 'Ce texte a pour autre avantage d utiliser des mots de longueur variable, essayant de simuler une occupation normale. La méthode simpliste consistant à copier-coller un court texte plusieurs fois (« ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ») a l inconvénient de ne pas permettre une juste appréciation typographique du résultat final.',
    longPrez: 'Il circule des centaines de versions différentes du Lorem ipsum, mais ce texte aurait originellement été tiré de l ouvrage de Cicéron, De Finibus Bonorum et Malorum (Liber Primus, 32), texte populaire à cette époque, dont l une des premières phrases est : « Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit... » (« Il n\'existe personne qui aime la souffrance pour elle-même, ni qui la recherche ni qui la veuille pour ce qu\'elle est... »).',
    firstPage: false,
    alignRight: true,
  },
  {
    id: 5,
    title: 'Hors sol',
    photo1: "el1.jpg",
    photo2: "el2.jpg",
    photo3: "el3.jpg",
    photo4: "el4.jpg",
    photo_profile: "photo_profile1.jpg",
    etpName: 'Morgane Munch',
    type: 'environnemental',
    tag1: '🌾 culture',
    tag2: '🌱 graine',
    tag3: '☘ vert',
    shortPrez: 'Plantons les graines de l\'avenir',
    littlePrez: 'pour suivre notre projet.',
    needs: '100 000',
    participation: '20 000',
    rentability: '5 000',
    etpCurriculum: 'Expert en utilisabilité des sites web et des logiciels, Jakob Nielsen souligne que l\'une des limites de l\'utilisation du faux-texte dans la conception de sites web est que ce texte n\'étant jamais lu, il ne permet pas de vérifier sa lisibilité effective. La lecture à l\'écran étant plus difficile, cet aspect est pourtant essentiel. Nielsen préconise donc l\'utilisation de textes représentatifs plutôt que du lorem ipsum. On peut aussi faire remarquer que les formules conçues avec du faux-texte ont tendance à sous-estimer l\'espace nécessaire à une titraille immédiatement intelligible, ce qui oblige les rédactions à formuler ensuite des titres simplificateurs, voire inexacts, pour ne pas dépasser l\'espace imparti.',
    longPrez: 'Contrairement à une idée répandue, le faux-texte ne donne même pas un aperçu réaliste du gris typographique, en particulier dans le cas des textes justifiés : en effet, les mots fictifs employés dans le faux-texte ne faisant évidemment pas partie des dictionnaires des logiciels de PAO, les programmes de césure ne peuvent pas effectuer leur travail habituel sur de tels textes.',
    firstPage: false,
    alignRight: false,
  },
  {
    id: 6,
    title: 'A.G.E.S.',
    photo1: "ages1.jpg",
    photo2: "ages2.jpg",
    photo3: "ages3.jpg",
    photo4: "ages4.jpg",
    photo_profile: "photo_profile2.jpg",
    etpName: 'Ahmed Ba',
    type: 'social',
    tag1: '👨‍🦳 âge',
    tag2: '👵🏻 retraite',
    tag3: '🙋🏽‍ participation',
    shortPrez: 'Activités inter-âges à la portée de tous.',
    littlePrez: 'pour jouer ensemble',
    needs: '100 000',
    participation: '20 000',
    rentability: '5 000',
    etpCurriculum: ' Par conséquent, l\'interlettrage du faux-texte sera toujours quelque peu supérieur à ce qu\'il aurait été avec un texte réel, qui présentera donc un aspect plus sombre et moins lisible que le faux-texte avec lequel le graphiste a effectué ses essais. Un vrai texte pose aussi des problèmes de lisibilité spécifiques (noms propres, numéros de téléphone, retours à la ligne fréquents, composition des citations en italiques, intertitres de plus de deux lignes...) qu\'on n\'observe jamais dans le faux-texte.',
    longPrez: 'Ce texte a pour autre avantage d\'utiliser des mots de longueur variable, essayant de simuler une occupation normale. La méthode simpliste consistant à copier-coller un court texte plusieurs fois (« ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ceci est un faux-texte ») a l\'inconvénient de ne pas permettre une juste appréciation typographique du résultat final.',
    firstPage: false,
    alignRight: true,
  },
];
