export const entreprises = [
  {
    id: 1,
    title: 'Ça commence par nous',
    photo1: "img-01.jpg",
    photo2: "img-02.jpg",
    photo3: "img-03.jpg",
    photo4: "img-04.jpg",
    photo_profile: "photo_profile1.jpg",
    etpName: 'Amina Saan',
    type: 'environnemental',
    tag1: 'manta',
    tag2: 'océan',
    tag3: 'plastique',
    shortPrez: 'Projet écolo-bobo-marin',
    littlePrez: 'pour construire un monde meilleur !',
    needs: '100 000',
    participation: '20.000',
    rentability: '5000',
    etpCurriculum: 'Amina a commencé à réflechir à ce projet enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ',
    longPrez: 'Chaque seconde, 253 kilos de plastique sont déversés dans les océans. Pour lutter contre la pollution plastique des océans, un autre mastodonte marin suscite lui aussi l\'espoir.Pour laver les océans, le Manta, un voilier de 70 mètres de long, doit permettre de collecter, trier et compacter en mer une grande quantité de macro-déchets plastiques flottant à la surface des océans.',
    firstPage: true,
  },
  {
    id: 2,
    title: 'Impact social',
    photo1: "img-1.jpg",
    photo2: "img-4.jpg",
    photo3: "img-2.jpg",
    photo4: "img-3.jpg",
    photo_profile: "photo_profile2.jpg",
    etpName: 'Annonay Youth Book Festival',
    type: 'social',
    tag1: 'livre',
    tag2: 'amitié',
    tag3: 'rencontre',
    shortPrez: 'Lire et créant du lien',
    littlePrez: 'pour lire avec nous !',
    needs: '30 000',
    participation: '10 000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
  {
    id: 3,
    title: 'Tech us',
    photo1: "tech-1.jpg",
    photo2: "tech-4.jpg",
    photo3: "tech-5.jpg",
    photo4: "tech-3.jpg",
    photo_profile: "photo_profile3.jpg",
    etpName: 'Logotech',
    type: 'tech',
    tag1: 'études',
    tag2: 'future',
    tag3: 'machine',
    shortPrez: 'La technologie au service de l\'environnement',
    littlePrez: 'et rentrez dans le monde de demain !',
    needs: '500 000',
    participation: '30 000',
    rentability: '10 000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
  {
    id: 4,
    title: 'Eduka',
    photo1: "queens-img-01.jpg",
    photo2: "queens-img-03.jpg",
    photo3: "queens-img-02.jpg",
    photo4: "queens-img-04.jpg",
    photo_profile: "photo_profile4.jpg",
    etpName: 'Julien Vidal',
    type: 'éducatif',
    tag1: 'éducation',
    tag2: 'jeunesse',
    tag3: 'opportunité',
    shortPrez: 'Le monde de demain sera façonné par ce que nous apprenons aujourd\'hui ',
    littlePrez: 'pour en savoir plus.',
    needs: '100 000',
    participation: '20 000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
  {
    id: 5,
    title: 'Hors sol',
    photo1: "queens-img-01.jpg",
    photo2: "queens-img-03.jpg",
    photo3: "queens-img-02.jpg",
    photo4: "queens-img-04.jpg",
    photo_profile: "photo_profile5.jpg",
    etpName: 'Julien Vidal',
    type: 'environnemental',
    tag1: 'culture',
    tag2: 'graine',
    tag3: 'vert',
    shortPrez: 'Plantons les graines de l\'avenir',
    littlePrez: 'pour semer des graines :)',
    needs: '100 000',
    participation: '20000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
  {
    id: 6,
    title: 'A.G.E.S.',
    photo1: "queens-img-01.jpg",
    photo2: "queens-img-03.jpg",
    photo3: "queens-img-02.jpg",
    photo4: "queens-img-04.jpg",
    photo_profile: "photo_profile6.jpg",
    etpName: 'Ahmed Ba',
    type: 'social',
    tag1: 'âge',
    tag2: 'retraite',
    tag3: 'participation',
    shortPrez: 'Activités inter-âges à la portée de tous.',
    littlePrez: 'pour jouer ensemble',
    needs: '100 000',
    participation: '20 000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
];
